### ISSUE TITLE
Минутки по синкапу. Запустить сайт

### ISSUE THREAD

**Issue by bmsdave** [piterjs/conf.piterjs.org#14]
1. Миша + Вадим - задеплоить 
2. После первого запуска - определиться с контекентом и минимумом с каторым можно анонсировать. Завести на это задачи.
3. Сделать эти задачи.
4. Зафиксировать информацию. и завести документ для фиксирования.
5. С Мишей по поводу почтовой рассылки.

**Comment by bmsdave** [comment]
6. Дождаться камеры, либо попросить снять за нас

**Comment by bmsdave** [comment]
7. Пообщаться с Алией по поводу рисования докладчиков и стикер паков.

**Comment by bmsdave** [comment]
8. Подумать насчет созвонов со спонсорами.

**Comment by bmsdave** [comment]
9. Продумать CoC

**Comment by bmsdave** [comment]
10. типографика нужно подумать про роллапы навигационные и прояую типографику.

**Comment by mike1pol** [comment]
1. Ready
