### ISSUE TITLE
 Открыть регистрацию

### ISSUE THREAD

**Issue by bmsdave** [piterjs/conf.piterjs.org#27]
Открыть регистрацию для посетителей.
Создать событие на timepad и слинковать его с сайтом

**Comment by mike1pol** [comment]
timepad done
https://piterjsconf.timepad.ru/event/1007647/

`<script type="text/javascript" async="async" defer="defer" charset="UTF-8" src="https://timepad.ru/js/tpwf/loader/min/loader.js" data-timepad-customized="50109" data-twf2s-event--id="1007647" data-timepad-widget-v2="event_register"></script>`

**Comment by bmsdave** [comment]
Готово, плагин если будем встраивать, то в отдельной таске
